name: flutter_mysql_sample
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #to encrypt passwords
  flutter_bcrypt:
  #to connect to database
  mysql1:
  #for your session
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  launcher_name:
  flutter_launcher_icons:

#run dart run launcher_name:main
launcher_name:
  default: "MySql Connection"

# for icon, don't forget to run flutter pub run flutter_launcher_icons
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
